name: forecast
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - scikit-image
  - seaborn
  - cassandra-driver
  - lime
  - shap=0.34
  - featuretools
  - statsmodels
  - workalendar
  - plotly
  - fbprophet
  - pip
  - pip:
    - pmdarima
    - natsort
prefix: /Users/digi/anaconda3/envs/forecast

